### PR TITLE
Add ShopSDK in final state.

### PR DESCRIPTION
**Pull request by 6100m**
Well Spotlight, that should about do it. We will finish this off together during that glitch session next week, but this is basically done.

### CODE REVIEW

**Comment by 6100m** [comment]
@spotlightishere Hey spotlight, it's in it's final state, and I have perfected it :) I tried to make a lot of the script's code accessible via classes, and this proved rather useful, as I could call them anywhere in the code. I have also made use of what I like to call "identifier padding" in which my code basically tells your code where things are located in a variable. Kinda like how aisles are labeled in a store, kind of.

**Comment by spotlightishere** [comment]
Could you please finalize changes before submitting a PR as to minimize commit count and allow for review?

**Comment by 6100m** [comment]
Yeah I can make a branch with less commits, one min :)

**Comment by spotlightishere** [comment]
Rather, please make a PR once you've finalized all edits (regardless of commit count, as long as everything is final) and it's in a state that can be reviewed.

**Comment by 6100m** [comment]
I think the edits are kinda final though Spotlight, I've finished up all of it :)

**Comment by 6100m** [comment]
Although yeah, I can make a finalized PR if needed though, one min

**Comment by 6100m** [comment]
Alright spotlight, I got the PR made :) Something cool I did was instead of obsfucating variables, I tried to make the implementation simple. I had to minify some of the names of the modules I used, but that's about it, it's about 95% un-minified, for easier readability :) Also, I even implemented a script run counter that tells you the UTC time it was ran at inside Datadog.

**Pull request closed without merging**
