### PR TITLE
WIP Shop Endpoints and Stuff

### PR DESCRIPTION
**Pull request by zurgeg**
**WIP**
- [ ] Add shop endpoints
- [ ] Add AS3 build tool submodule
- [ ] Add SWF to static

### CODE REVIEW

**Comment by 6100m** [comment]
@zurgeg 
#8 Established the link from Python to AS3. :) This should get done rather fast.

**Comment by 6100m** [comment]
@zurgeg Hey JG, I hope I am not bothering anything, but just wanted to give you a update on the selling part of the shop.
I have now simplified it to 500 less lines and it actually has a bonus functionality: It can randomly generate my aquarium tank dlc.
But yeah, I will be getting to the main script soon, and I am wondering if you and Spotlight have figured out a way to pull the shipping info into Python?

**Comment by larsenv** [comment]
All while being the worst code I think I've ever read.

[I used to do the same thing](https://gist.github.com/larsenv/9343d9e9fa6fa379214af73ba1448fba). Over more and more months I wrote better code and actually got to the point where it was functional, but yours...it's getting worse. 🤮

I don't mean to give toxic criticism, I just don't think you know how to write functional code. It looks like a trolling attempt honestly.

**Comment by 6100m** [comment]
I know Larsen, and yeah, I hope to improve this overtime like you did. Heck, with both of our services, you and me go on the same learning curve.

**Comment by zurgeg** [comment]
Stale.

**Pull request closed without merging**
