### PR TITLE
Add AS3 build tool submodule

### PR DESCRIPTION
**Pull request by 6100m**
This is probably the best library for it.

### CODE REVIEW

**Comment by zurgeg** [comment]
@6100m Thanks for this, one small problem, this library doesn't appear to generate an SWF...

**Comment by 6100m** [comment]
I noticed that too actually, apparently you code the SWF directly with flappy?

**Comment by zurgeg** [comment]
@6100m Hmm, we need an SWF statically generated somehow.

**Comment by 6100m** [comment]
Yeah, I'll find a different library, one sec :)

**Comment by 6100m** [comment]
@zurgeg Found a library that can create a SWF file and read and write data to it :)

**Comment by 6100m** [comment]
In turn, this library SHOULD be able to generate it :)

**Comment by spotlightishere** [comment]
We should create another repository for the SWF's source. This should not be dynamically generated.

**Comment by zurgeg** [comment]
In my opinion, we should build the SWF using this, but store it statically in a different repo.

**Comment by spotlightishere** [comment]
I don't think it would be too good to create a monorepo for all related source, especially as that may get tricky when v770/v512 are implemented. #7's approach of serving the SWF from here seems best, but source should be elsewhere.

**Pull request closed without merging**
