### PR TITLE
Implement #30, fix a couple errors and reformat a lot.

### PR DESCRIPTION
**Pull request by 6100m**
cc @spotlightishere Thy will be done, managed to achieve it.

I also reformatted config and reginfo while I was at it too.

Luckily, you only used the default black formatting level so I didn't have trouble with that lol.

### CODE REVIEW

**Comment by larsenv** [comment]
I thought you were blocked from contributing to WL24?

**Comment by larsenv** [comment]
I'm gonna be honest, this PR is different from your usual bogus. It probably will work. (Don't let that go to your head.)

I guess looking up the IP and getting the timezone with that is an interesting and feasible way of doing it? Because I don't think Wii no Ma will send country or region codes.

**Comment by SketchMaster2001** [comment]
Please test your scripts out before making PR's. For me it is constantly failing.

**Comment by larsenv** [comment]
Yes. Other devs fine it to be very annoying when the code isn't tested.

In fact, if you code without testing, you should find a different hobby.

**Comment by 6100m** [comment]
> Yes. Other devs fine it to be very annoying when the code isn't tested.
> 
> In fact, if you code without testing, you should find a different hobby.

Working it out/testing with Sketchmaster atm. It's weird, before this PR it can import the app variable from room just fine. Now, it just flat out refuses to after I put the code in. It won't import config either, even after I jumped it a directory back with ``from ... import`` Something is weird and I think I need your help, as this error should not happen at all.

**Review by zurgeg — CHANGES_REQUESTED** [review]
In `README.md`, you seem to have changed:
```md
# Useful for reading .flaskenv
pip3 install python-dotenv
```
to
```md
echo python-dotenv is useful for reading .flaskenv.
```
Were you using Windows CMD prompt and messed up your `echo` command?

Anyway, I'd suggest removing this change.

**Review by zurgeg — CHANGES_REQUESTED** [review]
In the example config, you create a whole new class for reginfo information. A possible solution is to use `from` imports to save imports.

**Comment by zurgeg** [comment]
> > Yes. Other devs fine it to be very annoying when the code isn't tested.
> > In fact, if you code without testing, you should find a different hobby.
> 
> Working it out/testing with Sketchmaster atm. It's weird, before this PR it can import the app variable from room just fine. Now, it just flat out refuses to after I put the code in. It won't import config either, even after I jumped it a directory back with `from ... import` syscall. Something is weird and I think I need your help, as this error should not happen at all but it does on Sketchmaster's personal server and I can't wrap my head around what's stopping it.
> Literally nothing in the hiearchy changed though, so why does it do it 🤔
> 
> EDIT: Never mind, it does work. https://prnt.sc/zwqwsu Ran my fork. Guess it is just sketchmaster.

@6100m Please note, in order for it to trigger an error, you must navigate to the URL causing the error. I will try on WSL later.

**Comment by SketchMaster2001** [comment]
A handy way to know if it is going to fail without searching up the link is turning on the Underground in `config.py`. When you start flask it should say `You have entered the Underground`. If it doesn't say that then it most likely will fail.

**Comment by zurgeg** [comment]
Closing while I fix some of the bugs here.

**Pull request closed without merging**
